---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
timezone: America/New_York
# lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "Zionism.is"
keywords:    "zionism, progressivism, liberal, democrat, zionist"
description: "Homepage for NYC-based advocacy group."
source_link: "http://zionism.is"
favicon:     "icons/favicon.ico"
touch_icon:  "icons/apple-icon.png"
google_analytics_key: UA-66673802-1


# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://zionism.is

baseurl: ""

# Site owner
owner: 
  name: Zionismiss
  email: info@zionism.is
  twitter: Zionismis
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: img/logo.jpeg # 160x160 px image for author byline

kramdown:
  auto_ids:  false

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
